Added support for " remote_config_encoding",fixes #62
spencerwooo/mihoro pull request #163
Opened 2024-09-07 15:08 UTC by RongDuJiKsp

### Description

Added support for the configuration item remote_config_encoding. When the configuration item is "plain", it will not be processed. When the configuration item is "base64", it will attempt to base64 decoding of the subscription address.

### Linked Issues

fixes #162

### Additional context

This is my first PR.I tested my code ,but I don't know the workflow.  If I am at fault, please correct me  :)

2024-09-11 03:22 UTC, spencerwooo commented
Thank you for this contribution! I will need some time to review your changes. In the meantime, please adjust according to the checks in the CI. :heart:

2024-09-18 09:09 UTC, spencerwooo commented on src/utils.rs
> +pub fn try_decode_base64_file_inplace(filename: &str) -> Result<()> {
I have updated the base64 file decoding function for better error handling, could you please check for any incorrect implementations or issues that I may have introduced here?

2024-09-18 09:12 UTC, spencerwooo requested changes
Considering the base64 file decoding fails silently and keeps the original file intact, I would prefer removing the requirement for enabling the decoding via `remote_config_encoding` configuration option, and always apply the base64 decoding regardless of the file format.

Could you please remove any related logic and update this PR? Thanks. :heart:

2024-09-19 02:05 UTC, spencerwooo approved these changes

2024-09-19 02:08 UTC, merged

2024-09-19 02:08 UTC, spencerwooo commented
Thanks again for the effort 🤩

2024-09-19 02:28 UTC, RongDuJiKsp commented
❤️